name: Install build to a device

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version to install'
                required: true
                default: latest

env:
    INSTALL_TIMEOUT: 15

jobs:
    install:
        runs-on: build-server
        steps:
            - uses: dsaltares/fetch-gh-release-asset@master
              
              with:
                version: ${{ github.event.inputs.run-on || 'latest' }}
                file: "Android.apk"
                target: "Releases/Android.apk"
                token: ${{ secrets.GITHUB_TOKEN }}
                
            - id: adb-install
              run: timeout "${{ env.INSTALL_TIMEOUT }}" adb install -r "Releases/Android.apk" && echo '::set-output name=MESSAGE::Installed the build.' || echo '::set-output name=MESSAGE::Failed to install the build.'
              
            - run: echo "${{ steps.adb-install.outputs.MESSAGE }}"
